### PR TITLE
7 Some enhancements and fixes for provider sign-up

### PR DESCRIPTION
**Pull request by aghimpu**
## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

### CODE REVIEW

**Comment by aghimpu** [comment]
Small note for @irinaBerendeeva87 and @lexlog that I initially forgot to add: 

The part of the feedback about the modal for adding employee is done just partially - we updated the text, but didn't sync all the visual details. 

This is done because we are now using there a generic notification modal instead of a custom one (like in Angular). So it's basically just an optimization to avoid adding a lot of extra code for modals that look very similar, instead they are now using shared code. So please just ignore some details like different button colors inside the modal.

**Comment by lexlog** [comment]
@aghimpu @dev-rminds could you please add a description for PR?

from top of my head don't recall what is this about and there is no connection with issue

**Comment by aghimpu** [comment]
https://github.com/teamforus/forus-frontend-react/pull/102

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
**Checked: /sign-up** 
Provider flow
✅ confirming link 
no error in console when you are on the "organization add step" and you have prefilled fields in the form
image
✅ field ADRES marked as a mandatory on the "office add" step
now you can't click "Next" on the offices steps without adding at least one office
✅  google map error on the offices page
❌ extra button "Map" at the  "Add your location(s)" page
✅ fixed the texts for the employee add modal
✅ added blue fill for the fund checkboxes on the "funds available" step
❌  some funds don't have subtitles with agreement to the [terms and conditions]
✅ fixed  the visual bug for the pagination on the "funds available" step
now there's no additional button and step for demo transactions if you don't use the app
❌ don't work dropdowns(organizations/ labels):
Selecting one organization/ label from the list, the others stop appearing. when choosing All organization/ label list did not appeare. 
 Screenshot 2024-06-18 at 10 47 28

**Comment by lexlog** [comment]
status - @aghimpu needs to discuss some changes with @irinaBerendeeva87, will do today

**Comment by aghimpu** [comment]
https://github.com/teamforus/forus-backend/pull/2240

**Review by irinaBerendeeva87 — DISMISSED** [review]
### Checked: /sign-up
**Provider flow**
✅ confirming link 
✅ field ADRES marked as a mandatory on the "office add" step
✅ google map error on the offices page
✅ no extra button "Map" at the "Add your location(s)" page
✅ texts for the employee add modal
✅ blue fill for the fund checkboxes on the "funds available" step
✅ subtitles with agreement to the [terms and conditions]
✅ pagination on the "funds available" step
✅ dropdowns(organizations/ labels):

**Review by lexlog — APPROVED** [review]
approved for further merge

**Review by lexlog — APPROVED** [review]

**Pull request merged**
