### PR TITLE
Wcag fix overlap issues

### PR DESCRIPTION
**Pull request by aghimpu**
https://github.com/teamforus/WCAG-audit-2023/issues/27
1. at 400% breadcrumbs shown on multiple lines in case of long texts
2. it was already fixed when we changed the layout of those cards (so no changes)

https://github.com/teamforus/WCAG-audit-2023/issues/22
1. When zoomed in at 150% or more, the profile menu is now shown
2. Content put below the map, without overlapping on Aanbieders page
3. maximum-scale and the user-scalable attributes were already removed (so no changes)

https://github.com/teamforus/WCAG-audit-2023/issues/23
1. Uitleg page - faq is now responsive
2. Search results - title is now shown on multiple lines
3. Declarations page overflow issues fixed

### CODE REVIEW

**Comment by dev-rminds** [comment]
For test scope I would mostly check these headers/titles on different implementations and + mobile
image
image
image

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
###  Checked: overlap issues
 ✅ at 400% breadcrumbs shown on multiple lines in case of long texts
❌ the profile menu  zoomed in at 150%
in 175% and more  in desktop/mobile version, the profile menu is not scrollable and not fully displayed
Screenshot 2024-07-03 at 10 20 32

❌ Content put below the map, without overlapping on Aanbieders page:
it's still overlapped 
mobile:
Screenshot 2024-07-03 at 15 22 43

web:
Screenshot 2024-07-03 at 15 21 31

**Uitleg page - faq**
✅ on Web 
❌ on mobile in landscape orientation
Screenshot 2024-07-03 at 16 29 51
Screenshot 2024-07-03 at 16 35 57
Screenshot 2024-07-03 at 16 35 50

✅ Search results - the title is now shown on multiple lines
Screenshot 2024-07-03 at 16 39 03

✅ Declarations page overflow issues fixed

**Comment by aghimpu** [comment]
@irinaBerendeeva87 Your first point of feedback is about a different menu, the mobile menu. I meant the sidebar you see on the desktop version of webshop, this one 
image
Besides the mobile menu seems to be scrollable for me as well (yes, not fully displayed, but it's scrollable)

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked: overlap issues
✅ the profile menu zoomed in at 150%
**Content put below the map, without overlapping on Aanbieders page**
✅ was fixed for goereeoverflakkee 
Screenshot 2024-07-08 at 16 51 30
❌ was fixed for Nijmegen
Screenshot 2024-07-08 at 16 52 06

**Uitleg page - faq**
✅ on Web
 On mobile in landscape orientation 
✅ was fixed for goereeoverflakkee 
❌ was fixed for Nijmegen
Screenshot 2024-07-08 at 17 07 42
Screenshot 2024-07-08 at 17 07 26

**Comment by aghimpu** [comment]
❌ was fixed for Nijmegen
I've tried it in different browsers and using different resolutions, repeating the exact same steps as Irina did (we had a call before too), but I couldn't reproduce it. I don't think this is a real issue, most likely it's related to the browser tools.

**Comment by irinaBerendeeva87** [comment]
> **Content put below the map, without overlapping on Aanbieders page**
@aghimpu 
I suggest fixing it also in Nijmegen. 
now it's like this:

https://github.com/teamforus/forus-frontend-react/assets/55141843/533d4876-87fb-4622-974d-964eb85c683e

**Comment by aghimpu** [comment]
@irinaBerendeeva87 
>> I suggest fixing it also in Nijmegen.

It was fixed on the provider details page, as mentioned previously in the report and in the PR description. 
But since you noticed how it also occurs on the office details page, I just made a new commit to fix it on both pages.

**Review by irinaBerendeeva87 — APPROVED** [review]
I checked overlapping and it was fixed for Nijmegen as well.

**Pull request merged**
