### PR TITLE
5 Migrate fund pages

### PR DESCRIPTION
**Pull request by dev-rminds**
@lexlog 
Since using the branch with reverted commits would complicate further merges to much (and we didn't merge anything to develop yet) I decided to recreate original branch and pr: 
https://github.com/teamforus/forus-frontend-react/pull/113

closed: 
https://github.com/teamforus/forus-frontend-react/pull/135

### CODE REVIEW

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked: /funds
❌ ✅
❌ Fonds page does not have pagination and counter
❌ URL doesn't contain parameters when active funds are selected:
?funds_type=active

**Header**
Buttons:
✅ Fonds toevoegen
✅ Lopend
✅ Archief
✅ Search field

**Table:**
✅ Data in a table 
✅ Statuses
✅ Message when there are no funds
❌ Elements in the list of funds don't have  a hover effect

**Meatballs menu** 
❌  some organizations have an extra item in the meatballs menu - Security
Screenshot 2024-06-05 at 11 40 09
✅ Button  Bekijken
✅ Button Bewerken
✅ Sponsor can not archive a fund with statuses: active, stopped, waiting
✅ Sponsor can archive a fund with active status
❌ Text "All implementations " has an ellipsis. 
Screenshot 2024-06-06 at 14 36 40

**Add fund**
❌ no text is added to the «Request button text» field on default 
Screenshot 2024-06-06 at 14 48 37
❌ text is not substituted when changing the value in the "Request method" field
❌ the field "Knoptekst aanvragen" doesn't have validation as a mandatory field
❌ extra section Categorieën
Screenshot 2024-06-06 at 15 43 50
❌ A date Calendar displays dates not only for the current month but also for the previous 
Screenshot 2024-06-06 at 16 15 37

**Fund:**
✅ After deleting a fund open page with funds
✅ Img, fund name and description
✅ Labels
❌ values in Gebruikt and Resterend rounded to integers
Screenshot 2024-06-06 at 17 10 56
❌Tabs  "Webshops" and "Bekijk aanvullingen" switched between each other 
Screenshot 2024-06-06 at 17 04 43
**Filter:**
❌  error 422 when add value 1 and 0 in each field  in Amount filter and then delete value 0 data not refreshed and see "No top-ups" and when I increase number I get errors in console. 
Screenshot 2024-06-06 at 17 31 43

**Fund formula:**
✅ data in the table is visible and correlates data in DB(https://github.com/teamforus/forus-frontend/pull/3317)

**Comment by lexlog** [comment]
* for info - [SPO part ](https://github.com/teamforus/SPO-2024-Smart-payout/issues/8)of this PR is tested and no feedback there

**Comment by aghimpu** [comment]
https://github.com/teamforus/forus-backend/pull/2233

**Comment by aghimpu** [comment]
@irinaBerendeeva87 
>> URL doesn't contain parameters when active funds are selected ?funds_type=active 
this part should be ignore, as an optimization we are now hiding the default funds_type value which is active, because it doesn't really bring anything to display it, only ?funds_type=archived is displayed

>> errors in console while adding symbols in a Short description field
I'll need more information on this one, not really sure how to reproduce it

>> Divider is "," instead of "." in the field "Reminder to replenish budget €"
seems to work fine for me even on https://dev.forus.io/sponsorreact/, besides it could as well be just a different decimal separator in the system locale (so not a real problem).

Everything else if fixed.

**Comment by lexlog** [comment]
@aghimpu thanks for an update!

@irinaBerendeeva87 could you please later on add all ignored findings to known issues list? https://docs.google.com/document/d/1hY2R7FQ2v2vNydX3Bcrq9Ltr3Qt1add6RDQhS1tM3hw/edit#heading=h.akysrdk8ojpz
( and from other PR-s as well )

**Comment by aghimpu** [comment]
https://github.com/teamforus/forus-backend/pull/2237

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked: /funds
❌ A date Calendar displays dates not only for the current month but also for the previous
✅ pagination and counter
✅ URL parameters
✅ hover
✅ meatballs menu
✅ Text "All implementations "
✅ Request method
✅ Categorieën
✅ Short description field
✅ Divider
✅ values in Gebruikt and Resterend 
✅ Tabs 
✅ Amount filter 
✅

**Review by irinaBerendeeva87 — APPROVED** [review]
### Checked: /funds
✅ A date picker 
✅ pagination and counter
✅ URL parameters
✅ hover
✅ meatballs menu
✅ Text "All implementations "
✅ Request method
✅ Categorieën
✅ Short description field
✅ Divider
✅ values in Gebruikt and Resterend
✅ Tabs
✅ Amount filter

**Review by lexlog — APPROVED** [review]

**Comment by lexlog** [comment]
no additional findings, approved PR for further merging

**Comment by lexlog** [comment]
@dev-rminds could you please take a look on conflict?
after you can merge this and left PRs if you want
https://github.com/teamforus/forus-frontend-react/pull/102
https://github.com/teamforus/forus-frontend-react/pull/141
or write me

**Pull request merged**
