### PR TITLE
1 Migrate voucher pages

### PR DESCRIPTION
**Pull request by aghimpu**

### CODE REVIEW

**Comment by lexlog** [comment]
this PR is a dependency for issue https://github.com/teamforus/DevOps/issues/818 with deadline of 1 of july and demo at 14 of june
@dev-rminds if it is possible, please take this PR first in compare with other high prio react PRs
( I wanted to make early review, but it is not compiling on demo )

**Comment by lexlog** [comment]
discussed with @dev-rminds - plan was to review this PR last, so he will just resolve conflicts and merge develop, what will be enough for early review and demo

**Comment by dev-rminds** [comment]
requires latest commit from https://github.com/teamforus/forus-backend/pull/2135
https://github.com/teamforus/forus-backend/pull/2135/commits/8e91666ea8f65a39758cc1f839cf49789329bf64

**Comment by dev-rminds** [comment]
@irinaBerendeeva87 
I have merged https://github.com/teamforus/forus-frontend-react/pull/140 into this pull request
Could you please test https://github.com/teamforus/forus-frontend-react/pull/140 scope on this branch as well?

**Comment by lexlog** [comment]
Checked: /vouchers

❌ **Vouchers list page**
  - ✅ funds dropdown
  - ✅ column names and amount, values

  - ✅ voucher actions ( meatballs menu )

  - ❌ Tooltips
    - ❌ missing translation on in_use tooltip 
       Screenshot 2024-06-17 at 12 32 17
     - ✅  pop-up when placing coursor on column name
  - ❌  Filters
    - ❌ Missing "Pas toe op" date in filters
     Screenshot 2024-06-17 at 12 35 56
  
    Screenshot 2024-06-17 at 12 36 10

    - ✅ Other filters
  - ❌ New voucher modal
    - ❌ Translation for "cancel" button on new voucher modal should be "Annuleren" instead of "Annuleer"
    - ✅ opening, closing modal, redirect to creating voucher page

  - ❌ Voucher generator
    - ❌ Translation for "cancel" button on voucher generator modal should be "Annuleren" instead of "Annuleer"
    - [ ] @lexlog Not tested upload
  - ❌ No URL parameters - ( @dev-rminds could you remind we planned to do it later, but if I'm correct it was about this PR? )
  - Exports
    - ❌ Missing option "All" in exporting vouchers
         Screenshot 2024-06-17 at 12 46 38
    - ❌ No pop-up after exporting vouchers from filters 
Screenshot 2024-06-17 at 12 49 42
    - ✅ turn on / off separate and all fields
    - ✅ select different export options for files and scope
- ✅ notes are visible

❌ **Vouchers details**

  - ❌ 
    - ❌ 
     - ✅ 
  - ❌ 
    - ❌ 
    - ✅ 
  - ❌ 

  - 
  - ❌ 
  - ❌ 
  - ❌ 
  - ❌ 
    - ❌ 
    - ❌ 
    - ✅ 
    - ✅
- ✅

**Comment by aghimpu** [comment]
@lexlog I think there are multiple deployment issues because several of those bugs, like "missing translation on in_use tooltip" or "Missing "Pas toe op" date in filters" and a few more just don't happen locally at all.

Here's that translation for example, so it's definitely present in the code https://github.com/teamforus/forus-frontend-react/blob/migrate-voucher-pages/react/src/dashboard/i18n/nl/pages/vouchers.pug.i18n.js#L96

**Comment by lexlog** [comment]
@aghimpu good note, found deployment issue, I will recheck findings

**Comment by lexlog** [comment]
updated list of findings after redeployment

**Comment by lexlog** [comment]
@aghimpu will add validation text for 422 while adding record

**Comment by lexlog** [comment]
after rechecking:

Fixed:
- ✅ No choice of product for product voucher, modal looks same as budget voucher modal
- ✅ No "personal records" block when creating new voucher ( if configured )
- ✅ Translation for "cancel" button on new voucher modal should be "Annuleren" instead of "Annuleer"
- ✅ Translation for "cancel" button on voucher generator modal should be "Annuleren" instead of "Annuleer"
- ✅ upload file with no values - no reaction ( in compare - Angular shows "No data was selected". only it would be good to have it red )
- ✅ if upload file and click outside of modal when there is warning, all buttons on vouchers page after closing modal will be locked
- ✅ cancel uploading when seeing validation warning is green instead of red ( not sure btw if it shouldn't be like on React ) ( not needed to be fixed)
- ✅  Missing option "All" in exporting vouchers
- ✅ No pop-up after exporting vouchers from filters 
- ✅ Field "providers" is not searchable on new transaction modal
- ✅ When reloading whole page, field "providers" is focused - no need to fix
- ✅ Focused on first field if reload page - no need to fix
- ✅ sometimes reproducable error when opening vouchers list

Not fixed
- ❌ @aghimpu please check in all modals on vouchers page have "Annuleren" button instead of "Annuleer"
- ❌ voucher generator - upload file with no headers - no error
- ❌ name of header when creating product voucher
Screenshot 2024-06-19 at 15 05 21
angular
Screenshot 2024-06-19 at 15 05 35

**Comment by lexlog** [comment]
@irinaBerendeeva87 there are only minor issues left to fix, so assigning you to review before they are fixed

**Review by irinaBerendeeva87 — COMMENTED** [review]
### Checked: /vouchers
**Vouchers list page**
 
✅List with data
✅Hover
✅ Tooltip 

**Tegoed aanmaken**
✅ Fields/Required fields
✅ error messages/notifications

**Voucher**
❌ Text wraps to another line when using a translator    **fixed in commit https://github.com/teamforus/forus-frontend-react/pull/123/commits/2b5e65080ab6ec8c9f6116e2725d4eb6f76906bc**
react 
Screenshot 2024-06-20 at 16 20 26
angular
Screenshot 2024-06-20 at 16 20 34

**Top-up**
❌ Button "Top up" appears with a delay

**New transaction**
❌ Fieald Provider counts spaces as characters and doesn't find an existing provider
Screenshot 2024-06-21 at 10 06 17

**Deactivate**
❌ Button  Cancel of the warning dialog does not lead to the previous screen. 

**Voeg een nieuwe eigenschap toe**     **fixed in commit  https://github.com/teamforus/forus-frontend-react/pull/123/commits/3fcfb6190414a2e82dd66a78cad8b00525fd8f72**
❌ additional field 'Er zijn niet meer eigenschappen beschikbaar.' in dropdown "Soort eigenschap"
Screenshot 2024-06-20 at 13 57 59

**Section History** 
❌ New transaction appeared in the section only after reload the page 
❌ No button "X" in a search field 
Screenshot 2024-06-21 at 10 22 32

**Section Transactions**   not reproduced/fixed
❌ Opening created transactions lead to empty screen and errors in the console
Screenshot 2024-06-20 at 17 08 57

### Checked: /product-vouchers
**Vouchers list page**
✅List with data
✅ Hover

❌ Text partially in English 
Screenshot 2024-06-21 at 10 53 14


**Section History** 
❌ No button "X" in a search field 

✅ voucher generator - upload file with no headers - no error
✅ name of header when creating product voucher

**Comment by lexlog** [comment]
status - since PR was waiting review of Valentin, he will start review and at the same time check errors above, if they are not fixed - he will fix it

**Comment by aghimpu** [comment]
>> Text partially in English (unauthorized error message)
image

This part should be ignore for now, the part which is in English comes from the backend and it happens in multiple other places too (obviously as a result this occurred in Angular JS).

**Comment by dev-rminds** [comment]
> > > Text partially in English (unauthorized error message)
> > > image
> 
> This part should be ignored for now, the part which is in English comes from the backend and it happens in multiple other places too (obviously as a result this occurred in Angular JS).

@lexlog @irinaBerendeeva87 
Since this is not react related, let's make a separate issue about it.

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked: /vouchers
**Vouchers list page**

✅List with data
✅Hover
✅ Tooltip

**Tegoed aanmaken**
✅ Fields/Required fields
✅ error messages/notifications

**Voucher**
✅ Text ( when using a translator)

**Top-up**
✅ Button "Top up" 

**New transaction**
✅ Field Provider counts spaces

**Deactivate** 
✅ Button Cancel 
❌ Button "To confirm"  without action 

https://github.com/teamforus/forus-frontend-react/assets/55141843/6685dd8b-6deb-4c62-b2d8-bb71f66513ea

**Section History**
❌ New transaction appeared in the section only after reloading the page
✅ button "X" in a search field

### Checked: /product-vouchers
**Vouchers list page**
✅List with data
✅ Hover

Section History
✅ No button "X" in a search field

✅ voucher generator - upload file with no headers - no error
✅ name of the header when creating a product voucher

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
@aghimpu I returned the task to revision because the comments have not been corrected. 
### Checked: /vouchers

**Deactivate dialog**
❌ Deactivate dialog appears again after successful deactivation. 

**Section History**
❌ A new log entry appears after reloading the page

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked: /vouchers
**Section Personal qualities**
❌ text in a dialog,   when sponsor delete created new characteristic. 
react 
Screenshot 2024-06-24 at 13 09 07

angular
Screenshot 2024-06-24 at 13 09 51

**Deactivate dialog**
✅ Deactivate dialog appears again after successful deactivation.

**Section History**
✅  A new log entry appears after reloading the page

**Review by irinaBerendeeva87 — APPROVED** [review]
All comments fixed).

**Review by lexlog — APPROVED** [review]

**Comment by lexlog** [comment]
the sacred moment has arrived

**Pull request merged**
