### PR TITLE
4 Add implementation configs and cms pages

### PR DESCRIPTION
**Pull request by ateamcms**

### CODE REVIEW

**Comment by lexlog** [comment]
Blocker problem which needs to be resolved to proceed testing:
- [ ] when saving empty draft me-app download page
Screenshot 2024-06-10 at 17 54 28

Minor issues:
- [ ] Markdown editor has preset value chosen even if it is not used ( see "B" (bold) preset ). On first load of page it was "I" )
Screenshot 2024-06-10 at 17 45 40
Screenshot 2024-06-10 at 17 52 59

- [ ] (reproduced on both angular and react) - missing/wrong translation
Screenshot 2024-06-10 at 17 58 06

@ateamcms (FYI)

**Comment by lexlog** [comment]
@irinaBerendeeva87 assigned you to re-test page, because I found not many issues

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked : /cms
**Webshop instellingen**
❌ Picture is always added at the beginning of the description editor page. 
**Startpagina content**
❌ error in a console while expanding blocks after reloading page 

Screenshot 2024-06-17 at 11 44 20

**Comment by ateamcms** [comment]
Picture is always added at the beginning of the description editor page. - fixed in [branch](https://github.com/teamforus/forus-frontend-react/tree/feature.add-system-notifications) (in pr https://github.com/teamforus/forus-frontend-react/pull/117)

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Retest : /cms
**Markdown**
✅ inserting img after text(fixed in https://github.com/teamforus/forus-frontend-react/pull/117)
❌ code braces disappeared at the markdown toolbar
Screenshot 2024-06-18 at 12 15 35

❌ no error message in a modal  when a sponsor is uploading img (10mb)
Screenshot 2024-06-18 at 11 50 30
✅ **Startpagina content**

**Comment by ateamcms** [comment]
code braces disappeared at the markdown toolbar - works with variable in storage
no error message in a modal when a sponsor is uploading img (10mb) - not in scope (because on angular will be same error), must go into enchancement issue

**Review by irinaBerendeeva87 — APPROVED** [review]
### Retest : /cms
**Markdown**
✅ inserting img after text(fixed in https://github.com/teamforus/forus-frontend-react/pull/117)
✅ code braces disappeared at the markdown toolbar


✅ no error message in a modal when a sponsor is uploading img (10mb)- for this issue I created a bug report https://github.com/teamforus/DevOps/issues/912
✅ Startpagina content

**Review by lexlog — APPROVED** [review]
approve for further merge

**Pull request merged**
