### PR TITLE
Add financial dashboard and financial overview

### PR DESCRIPTION
**Pull request by ateamcms**

### CODE REVIEW

**Comment by lexlog** [comment]
@aghimpu will review PR and compare with his branch financial overview part after pre-check issues. if there will be differences - write comment or contact Yaroslav to discuss

**Review by lexlog — APPROVED** [review]

**Comment by lexlog** [comment]
note - second to test

**Review by irinaBerendeeva87 — COMMENTED** [review]
QA review:

❌ browser tab shows Forus sponsot app value for tab name instead of name of the page
Screenshot 2024-05-14 at 17 03 42

**Financial overview page**
❌ on the Financieel overzicht page
no numerical data available in Saldo en uitgaven and Tegoeden sections
Screenshot 2024-05-14 at 16 37 20
✅ export

**Financial dashboard page**
❌ ✅

**Block with filters**:
✅ Fonds 
✅ Providers
✅ Postal codes
✅ Category
✅ Organization type
✅ Buttons: Maand, Kwartaal, Jaar

**Graph**
❌ Graph size is not restored when screen size changes
Screenshot 2024-05-14 at 17 56 17

**Financial totals**
❌ not displayed financial totals value
Screenshot 2024-05-14 at 18 01 40

 ❌ not displayed provider total spent and provider highest transaction
Screenshot 2024-05-14 at 18 04 50

**Comment by dev-rminds** [comment]
@lexlog could you please check if the right backend branch was deployed?

**Comment by dev-rminds** [comment]
@lexlog @irinaBerendeeva87 about the tab titles, we need a global fix for all pages, let's skip this on this branch and 
I will add the fix to this branch (https://github.com/teamforus/forus-frontend-react/pull/106) when I will finish the review.

**Comment by lexlog** [comment]
> @lexlog could you please check if the right backend branch was deployed?

@dev-rminds yes, problem was in branch, thanks ( @irinaBerendeeva87 please recheck findings )

**Review by lexlog — APPROVED** [review]

**Review by irinaBerendeeva87 — COMMENTED** [review]
I double-checked:

**Financial overview page**
✅  on the Financieel overzicht page 
numerical data available in Saldo en uitgaven and Tegoeden sections
✅  dropdowns in Tegoeden sections
✅ export

**Financial dashboard page**

**Block with filters:**
In all filters
❌  spaces are counted as characters during searching in search input(on Angular it doesn't count) - going to be fixed
Screenshot 2024-05-15 at 18 12 28

**Segmented buttons**
✅ Maand, Kwartaal, Jaar
✅ Totaal uitgegeven, Totaal transacties

**Graph**
❌ The graph size is not restored its size when screen size changes - will be fixed if won't take long time
❌ The graph disappeared when the sponsor switched to another browser tab and returned after a few seconds or minutes. It reappeared when you clicked on the field where the chart was supposed to be.
Screenshot 2024-05-16 at 09 43 59

**Financial totals**
✅ financial totals value are displayed
✅ provider total spent and provider highest transaction are displayed
❌ not possible to open 2 transactions simultaneously in Provider section. If one is open then the second is folded(in angular possible to open 2  transactions simultaneously)

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Retested: /financial-dashboard

**Financial dashboard page**
**Block with filters:**
In all filters
❌ spaces are counted as characters during searching in search input

**Graph**
✅ The graph size is restored 
**Financial totals**
✅ Possible to open 2 transactions simultaneously in Provider section.

**Review by irinaBerendeeva87 — APPROVED** [review]
### Retested: /financial-dashboard
**Financial dashboard page**
Block with filters:
✅ spaces are not counted as characters during searching in search input

**Pull request merged**
