### PR TITLE
fund criteria steps and rules feature

### PR DESCRIPTION
**Pull request by dev-rminds**
### Fund criteria overview
How to handle fund-criteria overview (first screen on the fund request) where the list of questions is listed.
Now it shows the full list of questions from the criteria, even if they are hidden before the rule is met.
Also for now if you have multiple criteria of the same record type but having different rules, it will show them only once and will use the record type name instead of the default/custom title.

### Validator: criteria overview
We should update the validator dashboard criteria overview pop-up for cases when multiple criteria of the same record-type are used (not sure how it should look like)
image

### Validator: fund request records editing
If a validator edits a record on fund request before approval, which is used in a rule for a different record it could lead to requester not getting the voucher after the approval an this will not be obvious for the validator.

### Limitations
- The criteria could only have more than 1 criteria of a record_type only if they have rules which do not overlap.
 - **wrong**
 - ```criteria1: [income >= 500 and income <= 1000>]```
 - ```criteria2: [income >= 900 and income <= 1500>]```
 - **correct**
 - ```criteria1: [income >= 500 and income <= 1000>]```
 - ```criteria2: [income > 1000 and income <= 1500>]```
 

- Organize the criteria in a manner that showcases the criteria used in the rules prior to the criteria where the rule is implemented.

### Prevalidations
The new fund-criteria rules validation is also applied to "create prevalidation modal" from sponsor dahsboard (only singular). 
Due to time restrictions, ongoing migration to react (pr for the page is still in review/feedback) and that it was not initially in the scope the frontend was not updated. 
The texts in the modal could be incorect for the fields where multiple criteria of the same type are used.
But the backend validation part should be up to date and allow you to fill only the information which should result in a voucher.
(should we make a separate issue to update the modal?)
image

### Regress
The old fund-request flows (criteria) should work just like before the update but better to test for regress (especially the custom scenarios like backoffice/auto-validation).

### Validator records editing (optional)
Validator dashboard: test editing fund request records before approval to check if editing while still in rules works fine.

### Fund criteria rules
- More than one rule for a criterion

- A chain of rules
   ex: fieldA > 5 => fieldB < 10-10-2020 => fieldC = [option1]

- All type of record_types: `bool`, `select`, `select_number`, `string`, `number`, `date`. optional: `iban`, `email`

- All types of criteria rule operators:
   ex: `<`, `<=`, `==`, `!=`, `>=`, `>`
   // (not all operators are supported by all types)

- Would be nice to test different scenarios when the request is partially approved and the requester has to apply again (to find potential issues/limitations).

- sorting criteria by the new column `order`

- when you have more than one criteria of the same type with different rules (example below) and you change 5 to 6, the value, validation error and files from criteria1 should be copied over to criteria2 and back if you change it back to 5. but if you change children to a value where both criteria are excluded by rules and the field is removed from the form the values are removed (should simplify resetting a chain of rules).
 - ex: criteria1: children > 2 and children <= 5, criteria2: criteria2: children > 6

### Fund criteria steps
- Add multiple steps 
- The criteria which are not assigned to any specific steps should be shown after the custom steps.
- Test changing criteria steps sorting by changing `order` column on `fund_criteria_steps` table (set `order` > 1000 to show them after criteria wihout step)

### CODE REVIEW

**Comment by dev-rminds** [comment]
## NOTES:
### Fund criteria overview
How to handle fund-criteria overview (first screen on the fund request) where the list of questions is listed.
Now it shows the full list of questions from the criteria, even if they are hidden before the rule is met.
Also for now if you have multiple criteria of the same record type but having different rules, it will show them only once and will use the record type name instead of the default/custom title.


### Validator: criteria overview
We should update the validator dashboard criteria overview pop-up for cases when multiple criteria of the same record-type are used (not sure how it should look like)
image



### Validator: fund request records editing
If a validator edits a record on fund request before approval, which is used in a rule for a different record it could lead to requester not getting the voucher after the approval an this will not be obvious for the validator.



### Limitations
- The criteria could only have more than 1 criteria of a record_type only if they have rules which do not overlap.
 - **wrong**
 - ```criteria1: [income >= 500 and income <= 1000>]```
 - ```criteria2: [income >= 900 and income <= 1500>]```
 - **correct**
 - ```criteria1: [income >= 500 and income <= 1000>]```
 - ```criteria2: [income > 1000 and income <= 1500>]```
 

- Organize the criteria in a manner that showcases the criteria used in the rules prior to the criteria where the rule is implemented.


### TEST SUGGESTIONS

### Prevalidations
The new fund-criteria rules validation is also applied to "create prevalidation modal" from sponsor dahsboard (only singular). 
Due to time restrictions, ongoing migration to react (pr for the page is still in review/feedback) and that it was not initially in the scope the frontend was not updated. 
The texts in the modal could be incorect for the fields where multiple criteria of the same type are used.
But the backend validation part should be up to date and allow you to fill only the information which should result in a voucher.
(should we make a separate issue to update the modal?)
image



### Regress
The old fund-request flows (criteria) should work just like before the update but better to test for regress (especially the custom scenarios like backoffice/auto-validation).

### Validator records editing (optional)
Validator dashboard: test editing fund request records before approval to check if editing while still in rules works fine.


### Fund criteria rules
- More than one rule for a criterion


- A chain of rules
   ex: fieldA > 5 => fieldB < 10-10-2020 => fieldC = [option1]


- All type of record_types: `bool`, `select`, `select_number`, `string`, `number`, `date`. optional: `iban`, `email`


- All types of criteria rule operators:
   ex: `<`, `<=`, `==`, `!=`, `>=`, `>`
   // (not all operators are supported by all types)


- Would be nice to test different scenarios when the request is partially approved and the requester has to apply again (to find potential issues/limitations).


- sorting criteria by the new column `order`


- when you have more than one criteria of the same type with different rules (example below) and you change 5 to 6, the value, validation error and files from criteria1 should be copied over to criteria2 and back if you change it back to 5. but if you change children to a value where both criteria are excluded by rules and the field is removed from the form the values are removed (should simplify resetting a chain of rules).
 - ex: criteria1: children > 2 and children <= 5, criteria2: criteria2: children > 6


### Fund criteria steps
- Add multiple steps 
- The criteria which are not assigned to any specific steps should be shown after the custom steps.
- Test changing criteria steps sorting by changing `order` column on `fund_criteria_steps` table (set `order` > 1000 to show them after criteria wihout step)

**Comment by RobinMeles** [comment]
@dev-rminds Can you check the merge conflicts?

Also for now tested fund criteria rules:
✅ More than one rule for a criterion
✅ A chain of rules
✅ All type of record_types
✅ All types of criteria rule operators
❌ Different scenarios when the request is partially approved and the requester has to apply again:

When the validator changes record of a criteria that is connected to a rule, the fund request bugs out. This is the case for a requester after approval by the validator (no steps to fill in, but still can apply for the fund):

The rule is:
Children_nth > 0
Age categories:
Eem_kind_0_tm_4_eligible_nth > -1
Eem_kind_4_tm_12_eligible_nth > -1
Eem_kind_12_tm_14_eligible_nth > -1
Eem_kind_14_tm_18_eligible_nth > -1

When a requester filled in 0 children, he/she does not get prompted to fill in the different age categories. But when the fund request is sent to the validator, and the validator edits the record children_nth from 0 to 1 or more, the requester gets prompted to apply for the fund again and it shows (probably since the rule states that the requester now has to fill in the age category questions):
image
image
image

Fund criteria steps:
✅ Add multiple steps
✅ The criteria which are not assigned to any specific steps should be shown after the custom steps.

Regress:
❌ Step/question is optional, but uploading attachement is required:
image
Above step is optional, but you still get prompted to upload a document (was already bug prior to this new functionality, but would be nice to fix in this PR)

Left to test (preferably after merge conflicts are resolved):
- Validator criteria overview
- Validator fund request record editing (partially tested, need to test more scenario's)
- Limitations (overlapping rules)
- Prevalidations as a sponsor

**Comment by lexlog** [comment]
sprint status discussion:
point "Different scenarios when the request is partially approved and the requester has to apply again" - this issue was already mentioned by Valentin before creating a PR and there was no clear solution as it didn't appear yet
Valentin propose to create a separate for this for @RobinMeles for round 2 of SPO project

**Comment by RobinMeles** [comment]
@dev-rminds could you check at this error?
image

**Comment by RobinMeles** [comment]
✅ Validator criteria overview
✅ Validator fund request record editing (partially tested, need to test more scenario's)
✅ Limitations (overlapping rules)
✅ Prevalidations as a sponsor

**Review by RobinMeles — APPROVED** [review]

**Pull request merged**
