### PR TITLE
Wcag some enhancements and fixes

### PR DESCRIPTION
**Pull request by aghimpu**
## Changes description & testing suggestions

- On declarations page all the errors are now in Dutch (some fields used to be in English), validation error texts were changed from something like  ‘het :field_name is verplicht' to ‘het :field_name is verplicht maar nog niet ingevuld’ where :field_name is the name of a specific field in Dutch
- On declarations page a visual indication was added to the required fields, also it was added to the file uploader
- On products page on the left side there 2 tabs named 'Volledig aanbod' and 'Mijn verlanglijstje', 'aria-pressed' attribute was added to the active tab
- On products page to the sorting dropdown an aria-labelledby="sort_by_label" was added to indicate to the screen readers that the element with the id 'sort_by_label' can serve as a label for the dropdown.

## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

### CODE REVIEW

**Comment by aghimpu** [comment]
https://github.com/teamforus/forus-backend/pull/2236

**Comment by dev-rminds** [comment]
@lexlog could you please check this comment first? 
probably not a blocker, but would be nice if not for now to still make an issue for future
https://github.com/teamforus/WCAG-audit-2023/issues/44#issuecomment-2179373653

**Comment by lexlog** [comment]
@dev-rminds created an issue https://github.com/teamforus/WCAG-audit-2023/issues/116

**Comment by irinaBerendeeva87** [comment]
@aghimpu  Please add information what was done in this pr

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked:
https://github.com/teamforus/WCAG-audit-2023/issues/44 :
**On declarations page:**
✅ all the errors are now in Dutch 
❌ validation error texts: ‘het :field_name is verplicht maar nog niet ingevuld’
missed validation error when not choosing Voucher:
Screenshot 2024-07-05 at 16 49 41

**validation error messages when field empty:**
✅ Title
✅ Amount
✅ IBAN
✅ Name of account holder
 ❌ error message when Name of account holder is short(like 3 letters) 
Screenshot 2024-07-08 at 13 13 29

@EmielForus 
My proposals to enhance some error messages for incorrect data for:
- Amount:
now we have : bedrag dient minimaal 0.1 te zijn.
my proposal: **B**edrag dient minimaal 0.1 te zijn.

- IBAN :
now we have :"Het IBAN-nummer is verplicht en moet geldig zijn."
my proposal: "Vul een geldig  IBAN-nummer in, bijvoorbeeld NL02ABNA0123456789"

- Name of account holder:
We  have error for  length of data in the field but we don't  check type of entered data. 
my proposal: allow only letters
note - optional, if there won't be easy option to do in laravel
 
✅ A visual indication for required fields 

https://github.com/teamforus/WCAG-audit-2023/issues/11 :
✅ aria-pressed="true"/"false"
✅ id="sort_by_label"

**Comment by aghimpu** [comment]
>> validation error texts: ‘het :field_name is verplicht maar nog niet ingevuld’
Done (added in the forus-backend PR).

I think the rest should be solved later if needed as they weren't even part of Janita's feedback and are rather just enhancements.

**Comment by lexlog** [comment]
discussed PR with Irina on status call - @aghimpu I agree that proposed by Irina changes are more enhancements, at least definitely not bugs ( asked @irinaBerendeeva87 to add them in separate block "out of report enhancements" )
but since we still have some time on this project for such enhancements ( to cover more possible cases with WCAG ), could you please take a look on them in this PR?

**Review by irinaBerendeeva87 — APPROVED** [review]
### Checked:
https://github.com/teamforus/WCAG-audit-2023/issues/44 :
On declarations page:
✅ all the errors are now in Dutch
✅ validation error texts: ‘het :field_name is verplicht maar nog niet ingevuld’
**Validation error messages when field empty:**
✅ Title
✅ Amount
✅ IBAN
**Fixed :**
✅missed validation error when not choosing Voucher
Screenshot 2024-07-12 at 14 15 58

✅ IBAN
Screenshot 2024-07-12 at 14 13 38

Screenshot 2024-07-12 at 14 13 47

✅ Error message when Name of account holder is short(like 3 letters)
Screenshot 2024-07-12 at 14 13 28
✅ Amount

✅ A visual indication for required fields

https://github.com/teamforus/WCAG-audit-2023/issues/11 :
✅ aria-pressed="true"/"false"
✅ id="sort_by_label"

**Pull request merged**
