### PR TITLE
Migrate BI Connection page

### PR DESCRIPTION
**Pull request by aghimpu**

### CODE REVIEW

**Comment by lexlog** [comment]
note - fourth to test for QA

**Comment by dev-rminds** [comment]
@irinaBerendeeva87 @lexlog 
Could be a deployment issue
image
image
image
image

**Comment by irinaBerendeeva87** [comment]
@dev-rminds I double-checked in a terminal after deploying branches on dev env.  And created the bug  and  I think it's connected to this task  https://github.com/teamforus/DevOps/issues/885

**Comment by lexlog** [comment]
status - @irinaBerendeeva87 needs to create separate temporary branch from sponsor.react and merge develop there and retest

**Review by irinaBerendeeva87 — COMMENTED** [review]
QA review:

✅ the button "Bevestigen" is clickable
✅ information button opens section with information

**Security**

✅ placeholder
✅ error message "The IP field is required" if click "Add IP address button".
✅ button Annuleren leads to the voucher page
✅ adding/deleting IP adress

✅ BI access if choose status: Uitgeschakeld

 **BI access if choose status: Ingeschakeld**

✅ fields URL and Hoofdertag have enabled button "content-copy"
✅ displayed checkboxes in section "Exportgegevens selecteren"
✅ notice when Top tag Expires in 2 days
❌   button Refresh: update does not change the tag

**Comment by aghimpu** [comment]
Token reset wasn't working just for the case when the connection was still in a disabled state (before switching to the enabled state and submitting the form). 
Otherwise it was working as expected. This behavior is exactly the same as the one in Angular.

However as I discussed it with Valentin as well allowing to reset the token for disabled connection wouldn't be a problem, so I opened a new PR for back-end given that it's a very small change.  
https://github.com/teamforus/forus-backend/pull/2228

**Review by irinaBerendeeva87 — APPROVED** [review]
**Double-checked problem with refreshing tag.** 
 Tag when status :
✅ Uitgeschakeld: refreshing change the tag in frontend and overwrite new tag 
✅Ingeschakeld: update change the tag in frontend and overwrite new tag

**Pull request merged**
