### PR TITLE
6 Migrate sponsor sign-up page

### PR DESCRIPTION
**Pull request by aghimpu**

### CODE REVIEW

**Comment by lexlog** [comment]
note - fifth to test for QA

**Comment by dev-rminds** [comment]
@irinaBerendeeva87 @lexlog 
Due to shared code between sponsor and validator sign-up, we need to retest the validator sign-up as well

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
**Checked: /sign-up**
 ### Sponsor sign-up flow

**Welkom page**
✅ button , image and text

**Maak een account** 
✅  link "inloggen met de me app"  leads to a page with QR code 
❌ email field  accepts only a value in the format: _@example.com/0@example.com(like in angular)
❌ enters email in the format: "irina+sponsorreact7@forus.i" lead to errors in console and a white screen
Screenshot 2024-05-27 at 14 25 15

✅ clearing the input field
✅ Button "Bevestigen" has an active and non-active state. 
✅  Error when email is incorrect
✅  Receiving a confirmation email
✅ email lead to page "Create organization"

**Organisatie aanmaken**
❌ The field "HERHAAL IBAN–NUMMER" doesn't have error text as mandatory when a sponsor clicks on "Volgende stap" without any data in the form. 
Screenshot 2024-05-27 at 14 08 34

**Comment by aghimpu** [comment]
@irinaBerendeeva87 

- The white screen on too many form submit requests was fixed
- IBAN confirmation validation works in the same way as it does in Angular - no error displayed near that field if the first IBAN field wasn't filled.
- Email format works the same it does in Angular too.

Can we create a separate issue later if needed for cases like IBAN confirmation and email format?

**Comment by irinaBerendeeva87** [comment]
> * The white screen on too many form submit requests was fixed
I checked after the fix and now there is no white screen. 
There is an error text: ''Too many requests. Please try again later.''  I have suggestion to avoid ambiguous error text  and use the text from the backend response:
 "title": "Te veel pogingen!",
"message": "Dit is poging 10, probeer het over N minuten opnieuw."

**Comment by irinaBerendeeva87** [comment]
**Checked: /sign-up**

### Provider sign-up flow

**Welkom page**
✅ button, link, image, and text

**Benodigdheden**
✅ Vorige stap, Volgende stap, image and text
✅ Click on Volgende stap  move to next screen Me-app downloaded

**Me-app downloaden**
✅ Vorige stap, Volgende stap, image and text
✅ links to the stores
✅  error messages
✅ Continue with email 
✅ Number of minutes change when clicking on Bevestigen
❌ confirming  link from email leads to  "Welcome page"
❌ to open "Maak een organisatie aan" page  after confirmation  provider should go through next 2 pages. 

**Maak een organisatie aan**
✅ form is displayed
✅ error message when the company name is too long
❌ error in console when image is too big (4MB)
Screenshot 2024-05-28 at 14 49 07

❌ error in console on page "Choose or create an organization" and click on previously created organization
 then click the button Add organization.  and fields filled in with previously created organization data. 
 
Screenshot 2024-05-28 at 16 47 44

**Add locations page**
❌ error with search and display on map  address 
Screenshot 2024-05-29 at 10 10 59
Screenshot 2024-05-29 at 10 10 31

**Add employees**
❌ <br/><br/> in the text on page
✅ create  two employees with equal email addresses
some funds don't have subtitles with agreement to the  [terms and conditions]
Screenshot 2024-05-28 at 17 44 25
❌ different dialog 
Screenshot 2024-05-29 at 10 05 48

**Register for the schemes**
❌ step border should be on Step 5
Screenshot 2024-05-29 at 10 27 25
✅ button Volgende stap appeared after choosing checkbox "skip step with registering for a scheme now"
❌  selected checkbox without blue fill
Screenshot 2024-05-29 at 10 32 57
❌ don't work dropdowns(organizations/ labels): 
Selecting one organization/ label from the list, the others stop appearing.
Screenshot 2024-05-28 at 17 03 55
❌ no space between counter and pagination
Screenshot 2024-05-28 at 17 06 02

**Organisatie aangemaakt**
❌ additional button "Doe een test betaling!"
❌  should be on a Step 6
Screenshot 2024-05-29 at 10 41 38

❌ Additional  step with Test betaling

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
**Checked: /sign-up**

### Provider sign-up flow

**Welkom page**
✅ button, link, image, and text

**Benodigdheden**
✅ Vorige stap, Volgende stap, image and text
✅ Click on Volgende stap  move to next screen Me-app downloaded

**Me-app downloaden**
✅ Vorige stap, Volgende stap, image and text
✅ links to the stores
✅  error messages
✅ Continue with email 
✅ Number of minutes change when clicking on Bevestigen
❌ confirming  link from email leads to  "Welcome page"
❌ to open "Maak een organisatie aan" page provider should go through next 2 pages. 

**Maak een organisatie aan**
✅ form is displayed
✅ error message when the company name is too long
❌ error in console when image is too big (4MB)
Screenshot 2024-05-28 at 14 49 07

❌ error in console on page "Choose or create an organization" and click on previously created organization
 then click the button Add organization.  and fields filled in with previously created organization data. 
Screenshot 2024-05-28 at 16 47 44

**Add locations page**
❌ don't work searching 
Screenshot 2024-05-29 at 10 10 31
Screenshot 2024-05-29 at 10 10 49
❌ Step border should be in Step 3
Screenshot 2024-05-29 at 11 03 33

**Add employees**
❌ Step border should be in Step 4
❌ tags  in the text on page
Screenshot 2024-05-29 at 11 24 43

✅ create  two employees with equal email addresses
some funds don't have subtitles with agreement to the  [terms and conditions]
Screenshot 2024-05-28 at 17 44 25

**Register for the schemes**
❌ Step border should be in Step 4
❌ don't work dropdowns(organizations/ labels): 
Selecting one organization/ label from the list, the others stop appearing.
Screenshot 2024-05-28 at 17 03 55
❌ no space between counter and pagination
Screenshot 2024-05-28 at 17 06 02
❌ selected checkboxes don't have a  blue fill
Screenshot 2024-05-29 at 10 32 57
Screenshot 2024-05-29 at 11 10 04
❌ some organizations don't have subtitles with  terms and conditions
Screenshot 2024-05-28 at 17 44 25
✅ "Volgende stap" button appeared when choose the checkbox to skip step with register for a scheme now. 

**Organisatie aangemaakt**
✅ Step border is in Step 6 when in a previous step skip step with register for a scheme now.  
✅ image, text
❌ additional button "Doe een test betaling!" lead to additional step "Test betaling"

**Comment by lexlog** [comment]
status - @irinaBerendeeva87 will check with @aghimpu about list above, @aghimpu mentiones there are points not related to PR
decided to:
- if point is not related to PR, but not on production, we should fix it in this PR
- if point is not related to PR, but on production - lets have separate issue

**Comment by aghimpu** [comment]
I checked the develop branch and it looks like all these points are not related to this PR. 
Also I didn't receive any console error on uploading big image files, so the error doesn't always trigger or it might be something else (needs investigation)?

I think it would be better to fix provider sign-up issues in this PR tho, even if they are not related it, just to avoid conflicts given that provider sign-up files got changed here as well.

**Comment by lexlog** [comment]
next steps:
- @aghimpu will open new PR with fixing all issues except uploading big files
- for big files problem @irinaBerendeeva87 will reproduce it again and check with @aghimpu after

**Comment by aghimpu** [comment]
I investigated that file upload issue with @irinaBerendeeva87 and it only happens when the image files are corrupted, so this is going to be ignored for now (also it's more related to the photo upload component than directly to the sign-ups).

Everything else for the provider sign-up is fixed in this PR https://github.com/teamforus/forus-frontend-react/pull/141.
Small note - slightly inconsistent step numeration isn't fixed either, because I think the Angular version isn't always accurate either (I've noticed for example that it jumps 2 steps in the steps numeration when you select the organization from the organization list).

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked: /sign-up
✅ ❌
**Validator sign-up flow**
**Welkom page**
✅ button, link, image
❌ Welkom  doesn't have a text
Screenshot 2024-06-07 at 14 35 44

**Hoe werkt het?**
✅ buttons, link, image, text

**Maak een account**
❌ Step doesn't have the text "Vul uw e-mail adres in om verder te gaan"
❌  Page saves its state when a validator clicks on Go back and then clicks the Sign-up button. The page opens on the page where the validator decided to go back. 
 
https://github.com/teamforus/forus-frontend-react/assets/55141843/13be643b-ab31-4beb-a09f-5ad3e93d2746

❌ Confirmation link from email leads to "Welcome page"
✅ Button "Ga naar dashboard" leads to "Aanvragen" page in the dashboard

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Retest: /sign-up

**Sponsor sign-up flow**
❌ Error in a concole after confirming email in a Step 1 of the flow 
error+sigh_up
✅ Errors in console and a white screen due to incorrect email
✅  Step3.

**Validator sign-up flow**
✅ ❌
✅ Welkom page
**Maak een account**
✅ Text "Vul uw e-mail adres in om verder te gaan"
✅ Page state
❌ Confirmation link : welkome page is shown first quickly and then Create page is displayed

**Comment by lexlog** [comment]
status - @aghimpu needs to discuss some changes with @irinaBerendeeva87, will do today

**Review by irinaBerendeeva87 — APPROVED** [review]
### Retest: /sign-up
**Sponsor sign-up flow**
✅ Errors in console and a white screen due to incorrect email
✅ Step3.
**Validator sign-up flow**

✅ Welkom page
Maak een account
✅ Text "Vul uw e-mail adres in om verder te gaan"
✅ Page state
✅ Confirmation link

**Comment by lexlog** [comment]
**Sponsor sign-up flow**
❌ If erase text on email field by "x" button, button "confirm" stays active
react
Screenshot 2024-06-20 at 11 47 21
angular
Screenshot 2024-06-20 at 11 47 26
❌ for the case above, if erase by "x" then click "log in with me app" and go back to login with email, erased text is appeared again
Screenshot 2024-06-20 at 11 48 26

**Making an account**
❌  Organisation type is not searchable
Screenshot 2024-06-20 at 11 57 10

**Comment by lexlog** [comment]
status - pr potentially ready for merge still, but needs conflict resolution at least

**Review by lexlog — APPROVED** [review]

**Comment by lexlog** [comment]
approved for further merge

**Review by lexlog — APPROVED** [review]

**Pull request merged**
