### PR TITLE
Wcag enhancements for tooltip and expand items

### PR DESCRIPTION
**Pull request by ateamcms**
## Changes description & testing suggestions
Was added:
- aria-expanded to Filteren button on mobile
- tooltip to IBAN field in reimbursement form
- made tooltip accessible from keyboard as button 
- aria-expanded to mobile menu button
- text for state of mobile menu button (if closed - "Meer", if opened - "Close")
- aria-expanded to mobile search toggle button
- aria-haspopup for search input (to indicate search results)
- aria-label «Close» for search close button 
- text for assistive software in pagination (for page numbers)

Fixed:
- fund_description_short ID for button "show more" in fund list

Removed:
- role button and tab index for h2 header in FAQ item list

Add tag if PR:
- [x] *Needs Translations* @lexlog @irinaBerendeeva87
- paginator.buttons.wcag_page
- IBAN nummer tooltip text in reimbursement form
- topnavbar.items.menu.close
- product.buttons.buy_label

## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

### CODE REVIEW

**Comment by dev-rminds** [comment]
@irinaBerendeeva87 
Not part of the issue but I made "Reserve" button focusable (regress from angular), but I did not add any wcag attributes.
The are also some other elements on the product details which are not focusable in react.

Do you think we need to add wcag attributes and make those elements focusable in this pr or later as part of a separate issue?

If you think we should do it in this pr, could you please ask @ateamcms to make the changes? 
Also If not, could you please create a separate issue?

image

**Comment by lexlog** [comment]
in terms of project hours we have some time, so we can do enhancements that Valentin proposed to increase each level

**Comment by dev-rminds** [comment]
@irinaBerendeeva87 I fixed the conflict, but since the components structure was changed in the develop, could you please test again the fund details page?

**Comment by irinaBerendeeva87** [comment]
@MariaForus we need your help with translations:
**- paginator.buttons.wcag_page :**
now we have :
Screenshot 2024-07-10 at 11 52 08

**- IBAN nummer tooltip text in reimbursement form:**
 we have : IBAN nummer must be format NL89BANK0123456789
Screenshot 2024-07-11 at 11 24 29

**- topnavbar.items.menu.close:**
Screenshot 2024-07-11 at 11 35 06

**- product.buttons.buy_label:**
For button Reserveren in an Aanbod detail page 
Screenshot 2024-07-11 at 11 40 04

**Review by irinaBerendeeva87 — APPROVED** [review]
### Checked:
**Was added:**

✅  aria-expanded to Filteren button on mobile
✅  tooltip to IBAN field in reimbursement form
✅  made tooltip accessible from keyboard as button
✅  aria-expanded to mobile menu button
✅  text for state of mobile menu button (if closed - "Meer", if opened - "Close")
✅  aria-expanded to mobile search toggle button
✅  aria-haspopup for search input (to indicate search results)
✅  aria-label «Close» for search close button
✅  text for assistive software in pagination (for page numbers)
**Fixed**:
✅  fund_description_short ID for button "show more" in fund list
**Removed**:
✅  role button and tab index for h2 header in FAQ item list

**Comment by MariaForus** [comment]
@irinaBerendeeva87 

I translated the words from the picture literally. If more precise translations are needed, I would require additional context and can review it again.

**- paginator.buttons.wcag_page :**

page 2 --> pagina 2 

**- IBAN nummer tooltip text in reimbursement form:**
IBAN-nummer moet het formaat NL89BANK0123456789 hebben

**- topnavbar.items.menu.close:**
Close --> Sluiten

**- product.buttons.buy_label:**
For button Reserveren in an Aanbod detail page

Open Reservation Form --> Open Reserveringsformulier

**Pull request merged**
