### PR TITLE
Add transaction bulk page, add upload transactions modal

### PR DESCRIPTION
**Pull request by ateamcms**

### CODE REVIEW

**Comment by lexlog** [comment]
qa feedback ( in progress, not ready yet ):
<details>
- [ ] "Bevestig" button is not blocked when no fields are chosen
Screenshot 2024-03-15 at 17 39 53
- [ ] Transaction costs shows as "-" if its 0 ( 0 on angular )
Screenshot 2024-03-15 at 17 40 30
Screenshot 2024-03-15 at 17 41 08
- [ ] lacking of field "status" in filters ( which was added during this week release )

</details>

**Comment by lexlog** [comment]
found out that changes from comment above were already added, but maybe forgot to reassign
@ateamcms could you please resolve conflicts and assign @dev-rminds ?

**Comment by lexlog** [comment]
note - first to test

**Review by irinaBerendeeva87 — COMMENTED** [review]
I checked:
 **Transaction page** :
 ❌ appeared an additional button "Instellingen"
Screenshot 2024-05-14 at 10 19 11

  **Bulktransacties page**:
❌  no additional parameters   /transactions?type=bulks in URL when opened Bulktransacties page. 
 **Transaction  detail**:
❌  doesn't display value in  Transaction costs  in Bulk transaction
(in angular the same Bulk transaction has value  €0.00)
Screenshot 2024-05-14 at 14 00 38

**Comment by lexlog** [comment]
Aleksei:
- filters "Bedrag" (amount) and Aantal don't filtering if set and then remove values ( if you fill in amount, then remove it, then fill in again - page content reloads, but doesn't change in compare with angular )
Screenshot 2024-05-15 at 11 55 32

- minor UI issue - double border on filters if keep cursor on the filter 
Screenshot 2024-05-15 at 10 45 41

- when set bulk payment to paid, individual transaction status is not updated to "paid" 
Screenshot 2024-05-15 at 11 38 31
Screenshot 2024-05-15 at 11 38 29

**Comment by ateamcms** [comment]
https://github.com/teamforus/forus-backend/pull/2221

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
Checked: 
✅ ❌ 
**Transaction page:**
❌ Pagination: when sponsor scrolls down the page and goes to the next transactions page, the next page load from the bottom. - @irinaBerendeeva87 will add to known issues in doc

❌When the sponsor in the transaction section goes to different pages with transactions and then puts the value in the amount,  the console will be filled with errors
Screenshot 2024-05-21 at 14 18 05



Screenshot 2024-05-21 at 14 11 53
Screenshot 2024-05-21 at 14 11 45

✅ disappeared an additional button "Instellingen"

**Transaction detail:**
✅ Transactiekosten € 0,-
✅ When set bulk payment to paid, individual transaction status is updated to "paid"

**Review by irinaBerendeeva87 — DISMISSED** [review]
**Retested**:
✅ Button "Maak nu een bulktransactie", Bundel numbers and Total amount
✅ Transactie in (dagen)
✅  Upload button disappears after file removal

**Pull request merged**
