### PR TITLE
Wcag alternative texts

### PR DESCRIPTION
**Pull request by aghimpu**

### CODE REVIEW

**Comment by aghimpu** [comment]
@irinaBerendeeva87 I added https://github.com/teamforus/WCAG-audit-2023/issues/5. It's a really small one (just the alt text for voucher images on the voucher details page).

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked: alternative text
❌ ✅
✅ Aanvraag busvoordeelabonnement (proces)
✅ Header logo alt-text
✅ aria-hidden="true"
✅ title
❌ Logo DigiD. There is no alt= "logo DigiD" 
❌ no alt text : alt= "Sluit zoeken"

**Comment by aghimpu** [comment]
@irinaBerendeeva87 "Sluit zoeken" isn't added directly as an alt text, because that "cross" isn't an actual image but a Material Design Icon, so instead I added a label using the aria-label attribute to its div container and it should serve a similar purpose.

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
**Checked: alternative text**
✅ Logo DigiD
✅ aria-label="Sluit zoeken"
✅ aria-hidden="true" for svg elements
✅ images with empty alt-attribute.
✅ aria-hidden="true" for Aanmelden als aanbieder icon
❌ NO aria-hidden="true" for  Arrow icons  
Screenshot 2024-07-02 at 11 15 43
❌ NO aria-hidden="true" for  Arrow icon in Aanvragen
Screenshot 2024-07-02 at 11 42 38
❌ NO  blank alt attribute  for New declaration icon
✅ aria-hidden="true" for elements "Bekijk meer"
✅ aria-hidden="true" for elements "Bekijk de kaart"
✅ aria-hidden="true" for elements "Aanvragen"

**Comment by aghimpu** [comment]
@irinaBerendeeva87 svg elements can't have an alt attribute, so I had to add an aria-label="" to the parent element.

**Review by irinaBerendeeva87 — COMMENTED** [review]
### Checked: alternative text
✅ Logo DigiD
✅ aria-label="Sluit zoeken"
✅ aria-hidden="true" for svg elements
✅ images with empty alt-attribute.
✅ aria-hidden="true" for Aanmelden als aanbieder icon
✅  aria-hidden="true" for Arrow icons
@aghimpu we need a call about: blank alt attribute for New declaration icon

**Review by irinaBerendeeva87 — APPROVED** [review]
Approve, all was fixed

**Pull request merged**
