### PR TITLE
2 Add sponsor providers

### PR DESCRIPTION
**Pull request by ateamcms**

### CODE REVIEW

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked : /providers
❌ ✅

❌ Errors while  opening page /providers
Screenshot 2024-06-10 at 17 02 20

❌ Circular page load  and errors in a console after clicking on alert 
and endpoint contain null: /providers/null
Screenshot 2024-06-11 at 10 34 21

❌ Click on dropdown is  lead to errors in a console
Screenshot 2024-06-11 at 10 43 09
❌  error "Router Error: route "sponsor-fund-unsubscriptions" not found!" in pagination

**Comment by ateamcms** [comment]
added missing fund unsubsriptions page

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
**Checked : /providers**

❌ opening "fund unsubsriptions page"(/fund-unsubscriptions)
lead to errors and white screen:
URL has parameters: /fund-unsubscriptions?page=1&per_page=10
Screenshot 2024-06-14 at 13 18 56
Screenshot 2024-06-14 at 13 19 43

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked : /providers
❌ hover fund at the page(../fund-unsubscriptions) does not change color
✅ filters

**Comment by ateamcms** [comment]
@irinaBerendeeva87 fixed hover effect

**Comment by lexlog** [comment]
after rechecking, only minor UI problems

- ❌ Incorrect translation on unsubscription tab ( no funds instead of no subscriptions )
Screenshot 2024-06-18 at 16 36 33

- ❌ breadcrumbs for 3rd and 4th level are not blue
React
Screenshot 2024-06-18 at 16 52 55
Angular
Screenshot 2024-06-18 at 16 53 44

-❌ Accepteren button have "x" in design instead of checkmark on provider details page ( when there is active request from provider for a fund )
React
Screenshot 2024-06-18 at 16 56 33
Angular
Screenshot 2024-06-18 at 16 56 56

-❌ Template for discount amount on product edit/create page should be 0 instead of specific value 20
Screenshot 2024-06-18 at 17 02 10

**Comment by ateamcms** [comment]
@lexlog made fix

**Comment by lexlog** [comment]
all points above are fixed, approving PR for further merge

**Review by lexlog — APPROVED** [review]

**Pull request merged**
