### PR TITLE
Change browser validation message for email input webshop login

### PR DESCRIPTION
**Pull request by ateamcms**
## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

### CODE REVIEW

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked:

✅ error message when empty field

**The same error message when:**
❌ add special characters in email  like this : #$#@!@#$%%@forus.io
Screenshot 2024-06-24 at 15 41 33

❌ with "@" and without "@"
Screenshot 2024-06-24 at 14 57 36

❌ too long email 
Screenshot 2024-06-24 at 15 12 49

**Comment by dev-rminds** [comment]
@irinaBerendeeva87 
The error above "U heeft geen e-mailadres ingevuld, of U heeft geen geldig e-mailadres ingevuld" is the only error message and case provided in the issue (which is also generic and should probably be enough to cover all but the last "too long case"). 

To cover other cases a list of cases and error messages needs to be provided.

@EmielForus what do you think about this issue?
Do you think we need to have custom messages for the examples above or the current message is enough https://github.com/teamforus/forus-frontend-react/pull/162#pullrequestreview-2136140582?

**Comment by irinaBerendeeva87** [comment]
> @irinaBerendeeva87 The error above "U heeft geen e-mailadres ingevuld, of U heeft geen geldig e-mailadres ingevuld" is the only error message and case provided in the issue (which is also generic and should probably be enough to cover all but the last "too long case").
> 
> To cover other cases a list of cases and error messages needs to be provided.
> 
> @EmielForus what do you think about this issue? Do you think we need to have custom messages for the examples above or the current message is enough [#162 (review)](https://github.com/teamforus/forus-frontend-react/pull/162#pullrequestreview-2136140582)?

Let's make life better for all our users by doing this:

image
 or this 
 
image

Users are already going to be frustrated when they get an error message—don’t make it worse by placing the blame on them. This means we should avoid using phrases like “you did” or “you didn’t” when explaining what went wrong. Instead, keep directives specific to what the user needs to do to remedy the problematic action. If the email address they entered is incorrect, then say “Please enter a valid email address using the following format: joe@example.com” instead of telling the user: “You entered your email incorrectly.”

**Comment by EmielForus** [comment]
> @irinaBerendeeva87 The error above "U heeft geen e-mailadres ingevuld, of U heeft geen geldig e-mailadres ingevuld" is the only error message and case provided in the issue (which is also generic and should probably be enough to cover all but the last "too long case").
> 
> To cover other cases a list of cases and error messages needs to be provided.
> 
> @EmielForus what do you think about this issue? Do you think we need to have custom messages for the examples above or the current message is enough [#162 (review)](https://github.com/teamforus/forus-frontend-react/pull/162#pullrequestreview-2136140582)?

I like the proposal from Irina (“Please enter a valid email address using the following format: joe@example.com” ) Sounds more neutral

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked:
@ateamcms  please add attribute required and add text ("Vul alstublieft een geldig e-mailadres in, bijvoorbeeld naam@voorbeeld.com.") for the case when  email field is empty
Screenshot 2024-07-01 at 16 40 30


✅ error message when :
- email doesn't have "@" ;
Screenshot 2024-07-01 at 11 45 55

- special characters in email ;
Screenshot 2024-07-01 at 13 02 31

- error message when email without domain name;
Screenshot 2024-07-01 at 13 03 07

- error message when email with domain name and without username;
Screenshot 2024-07-01 at 11 50 36

**Comment by ateamcms** [comment]
@irinaBerendeeva87 added message

**Pull request merged**
